### ISSUE TITLE
[Bug]: Context menu not showing until refresh the page and it's not desapear after changing page

### ISSUE THREAD

**Issue by saifonglee** [aymanalhattami/filament-context-menu#2]
### What happened?

1. the contextMenu appear correctly when refresh the page. but if i come to the page without refreshing it, the contextMenu not showing.
2. when i click link on the contextMenu to change page, in the targeted page, i have to refresh before seing the conextMenu. and the contextMenu do not disapear when go back to the previous page even if i click on Esc key or refresh the page. 

### How to reproduce the bug

1. add the PageHasContextMenu to the page
2. add the getContextMenuActions function and set the contextMenu actions
3. test on the targeted pages.

### Package Version

1.0.0

### PHP Version

8.2.17

### Laravel Version

10.x

### Which operating systems does with happen with?

Linux

**Comment by aymanalhattami** [comment]
Check browser console to see if there is an error

**Comment by saifonglee** [comment]
![Capture d’écran du 2024-04-29 09-45-34](https://github.com/aymanalhattami/filament-context-menu/assets/20534640/e71efab1-db90-43c1-876a-86b975b6a7a0)

**Comment by aymanalhattami** [comment]
These errors not related to the package

**Comment by saifonglee** [comment]
so there is no error, but it still not workong well. i've to refresh the page to be able to see the contextMenu

**Comment by zajinx** [comment]
I think this happens only in SPA mode, if I enable it when I navigate from a page without context menu enable to one with context menu it doesn't load up, but if access the page directly it works no problem

**Comment by aymanalhattami** [comment]
PRs are welcome

**Comment by JoshuaSigaban** [comment]
Yes @zajinx looks like the issue is when using ->spa()
Also experiencing the same issue

**Comment by aymanalhattami** [comment]
fixed https://github.com/aymanalhattami/filament-context-menu/pull/7
