### ISSUE TITLE
[Bug]: Weirdly Package Overrides Create Action

### ISSUE THREAD

**Issue by PovilasKorop** [aymanalhattami/filament-context-menu#3]
### What happened?

When I just add your Trait, my previously-working Create button turns into a modal action without... action?

### How to reproduce the bug

See video:
https://www.loom.com/share/2b63fd0f88e4468db5d468ed51efc973?sid=2f25bdf0-48a4-49b6-8605-aed5ad5b8d0c

Maybe it's my local code and I have extra things coded somewhere, but please try to reproduce on your end.

### Package Version

Latest

### PHP Version

8.2

### Laravel Version

11.0

**Comment by aymanalhattami** [comment]
I will check it

**Comment by aymanalhattami** [comment]
This issue has been fixed on [1.0.1](https://github.com/aymanalhattami/filament-context-menu/releases/tag/1.0.1)
